using PascalCompiler.Lexer;
using PascalCompiler.Parser.Nodes;
namespace PascalCompiler {
    public static class CommonConstants {
        public enum ServiceWords {
            NONE,
            ARRAY,
            BEGIN,
            CASE,
            CONST,
            DO,
            DOWNTO,
            ELSE,
            END,
            FOR,
            FUNCTION,
            IF,
            OF,
            PROCEDURE,
            PROGRAM,
            RECORD,
            REPEAT,
            THEN,
            TO,
            TYPE,
            UNTIL,
            VAR,
            WHILE,
            AND,
            OR,
            XOR,
            NOT,
            DIV,
            MOD,
            PLUS,
            MINUS,
            MULTIPLY,
            DIVIDE,
            ASSIGN,
            EQUAL,
            GREATER,
            LESSER,
            GREATER_OR_EQUAL,
            LESSER_OR_EQUAL,
            NOT_EQUAL,
            ELLIPSIS,
            COLON,
            POINT,
            COMMA,
            SEMICOLON,
            LEFT_ROUND_BRACKET,
            RIGHT_ROUND_BRACKET,
            LEFT_SQUARE_BRACKET,
            RIGHT_SQUARE_BRACKET,
            OUT
        }

        public static Dictionary<ServiceWords, string> ServiceWordsDict = new Dictionary<ServiceWords, string>() {
            { ServiceWords.ARRAY, "array" },
            { ServiceWords.BEGIN, "begin" },
            { ServiceWords.CASE, "case" },
            { ServiceWords.CONST, "const" },
            { ServiceWords.DO, "do" },
            { ServiceWords.DOWNTO, "downto" },
            { ServiceWords.ELSE, "else" },
            { ServiceWords.END, "end" },
            { ServiceWords.FOR, "for" },
            { ServiceWords.FUNCTION, "function" },
            { ServiceWords.IF, "if" },
            { ServiceWords.OF, "of" },
            { ServiceWords.PROCEDURE, "procedure" },
            { ServiceWords.PROGRAM, "program" },
            { ServiceWords.RECORD, "record" },
            { ServiceWords.REPEAT, "repeat" },
            { ServiceWords.THEN, "then" },
            { ServiceWords.TO, "to" },
            { ServiceWords.TYPE, "type" },
            { ServiceWords.UNTIL, "until" },
            { ServiceWords.VAR, "var" },
            { ServiceWords.WHILE, "while" },
            { ServiceWords.AND, "and" },
            { ServiceWords.OR, "or" },
            { ServiceWords.XOR, "xor" },
            { ServiceWords.NOT, "not" },
            { ServiceWords.DIV, "div" },
            { ServiceWords.MOD, "mod" },
            { ServiceWords.PLUS, "+" },
            { ServiceWords.MINUS, "-" },
            { ServiceWords.MULTIPLY, "*" },
            { ServiceWords.DIVIDE, "/" },
            { ServiceWords.ASSIGN, ":=" },
            { ServiceWords.EQUAL, "=" },
            { ServiceWords.GREATER, ">" },
            { ServiceWords.LESSER, "<" },
            { ServiceWords.GREATER_OR_EQUAL, ">=" },
            { ServiceWords.LESSER_OR_EQUAL, "<=" },
            { ServiceWords.NOT_EQUAL, "<>" },
            { ServiceWords.ELLIPSIS, ".." },
            { ServiceWords.COLON, ":" },
            { ServiceWords.POINT, "." },
            { ServiceWords.COMMA, "," },
            { ServiceWords.SEMICOLON, ";" },
            { ServiceWords.LEFT_ROUND_BRACKET, "(" },
            { ServiceWords.RIGHT_ROUND_BRACKET, ")" },
            { ServiceWords.LEFT_SQUARE_BRACKET, "[" },
            { ServiceWords.RIGHT_SQUARE_BRACKET, "]" },
            { ServiceWords.OUT, "out"}
        };

        public static readonly string ProjectPath =
            Directory.GetParent(Environment.CurrentDirectory)!.Parent!.Parent!.FullName;
    }
}
